// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAArgxknpVuE3xeOJIvTrrPegEWrs-xTwM',
    appId: '1:522108700851:web:65b8658d4344649ef088c6',
    messagingSenderId: '522108700851',
    projectId: 'bookmyspace-9203a',
    authDomain: 'bookmyspace-9203a.firebaseapp.com',
    storageBucket: 'bookmyspace-9203a.appspot.com',
    measurementId: 'G-WLMP08ZV41',
  );

  static const FirebaseOptions android = FirebaseOptions(
      apiKey: 'AIzaSyD74Z7RV4FCuezw6OIarN3waDGHFI4sl3M',
      appId: '1:522108700851:android:51e919449b4a0f69f088c6',
      messagingSenderId: '522108700851',
      projectId: 'bookmyspace-9203a',
      storageBucket: 'bookmyspace-9203a.appspot.com',
      authDomain:
          '522108700851-osqt0b9egicav0rc5ughkpaf5q73csv9.apps.googleusercontent.com');

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtF4b8aSRL-DM0ZORYmbcZ2a6RVA9-KAs',
    appId: '1:522108700851:ios:a28af3e75edef9daf088c6',
    messagingSenderId: '522108700851',
    projectId: 'bookmyspace-9203a',
    storageBucket: 'bookmyspace-9203a.appspot.com',
    iosClientId:
        '522108700851-dnfugfm3l7ncr0k6gd3dbd3gmqto5fq3.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookmyspace',
  );
}
